---
abstract: 'Simple Syntax Highlight Engine'
author:
  - 'Sugama Keita <sugama@jamadam.com>'
  - 'Andreas K. Huettel <mail@akhuettel.de>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1002, CPAN::Meta::Converter version 2.150005'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Syntax-Highlight-Engine-Simple
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: '0'
  encoding: '0'
  version: '0'
version: '0.10'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
